# Generated by Django 4.0.3 on 2022-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carstable',
            options={'verbose_name': 'Машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='carstable',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='carstable',
            name='photo',
            field=models.ImageField(upload_to='photos/cars', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carstable',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Модель Машины'),
        ),
    ]
