# Generated by Django 4.0.3 on 2022-04-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstable',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
    ]
