# Generated by Django 4.0.3 on 2022-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carstable_is_published_carstable_time_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория Машин', 'verbose_name_plural': 'Категория Машин'},
        ),
        migrations.AlterField(
            model_name='carstable',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус Публикации'),
        ),
        migrations.AlterField(
            model_name='carstable',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='carstable',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
    ]
