# Generated by Django 4.0.3 on 2022-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_carstable_price_alter_carstable_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=100, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
            ],
        ),
        migrations.AlterField(
            model_name='carstable',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена | BYN'),
        ),
    ]
