# Generated by Django 4.0.3 on 2022-04-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_carstable_price_alter_carstable_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstable',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена | BYN'),
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=100, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.carstable', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-time_create', 'choice'],
            },
        ),
    ]
