# Generated by Django 4.0.3 on 2022-04-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ordertable_alter_carstable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.carstable', verbose_name='Машина'),
        ),
    ]
