# Generated by Django 4.0.3 on 2022-04-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_feedbacktable_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktable',
            options={'ordering': ['-time_create'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
