# Generated by Django 4.0.3 on 2022-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_feedbacktable_author_alter_ordertable_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertable',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='choice',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Номер телефона'),
        ),
    ]
