# Generated by Django 4.0.3 on 2022-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_ordertable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
